baseURL = "https://tutorials.groupdocs.com/signature"

# Google Tag Manager settings
[params.gtm]
gtm_id = "GTM-WZTNN8"

[[deployment.targets]]
name = "Production"
URL = "s3://tutorials.groupdocs.com/?prefix=signature/&region=us-west-2"
